### PR TITLE
Mask the marketplace value

### PR DESCRIPTION
**Pull request by sharidas**
Mask the marketplace value

Signed-off-by: Sujith H <sharidasan@owncloud.com>

### CODE REVIEW

**Comment by PVince81** [comment]
I think config:list is not the same as config report.

Also there should already be a location where the list of excluded keys exist. Please find said location and add the marketplace key there.

**Comment by sharidas** [comment]
> I think config:list is not the same as config report.

Ouch. I read `config:list` and somehow mapped to configreport :( My apologies...

Shouldn't we mask here in the config report too?

**Comment by PVince81** [comment]
Isn't it already masked here ? That method is called getFilteredValue()

**Comment by sharidas** [comment]
> Isn't it already masked here ? That method is called getFilteredValue()

getFilteredValue() wasn't picking the sensitive value because it wasn't defined in the SystemConfig. Since we have PR: https://github.com/owncloud/core/pull/30916 here, I am closing this PR.

**Pull request closed without merging**
