### PR TITLE
[stable10] Backport of Add oc tables and details to report

### PR DESCRIPTION
**Pull request by sharidas**
Add oc table and details to the report.

Signed-off-by: Sujith H <sharidasan@owncloud.com>

### CODE REVIEW

**Comment by sharidas** [comment]
Original PR https://github.com/owncloud/configreport/pull/84

**Comment by sharidas** [comment]
Ouch horracle :(

**Comment by sharidas** [comment]
> @sharidas are there any code differences in the configreport app between master and stable10 ?
> 
> if not then it could be a core change between stable10/master... would need bisecting.

There is no code differences between stable10/master branch. The only difference is in the test ( though marginal ). I will do the bisecting and share the results.

**Comment by sharidas** [comment]
As per discussion, assigning the PR to @PVince81 . Bascially helping me, with the oracle, by bisecting master v/s stable10.

**Comment by PVince81** [comment]
@sharidas huh, how come it's green now ?

**Comment by sharidas** [comment]
Eeew something is wrong here https://drone.owncloud.com/owncloud/configreport/342/21.

Now related to this failure:
- [ ] Do we need php lint on each test in drone? ( I do see in most of the tests )
- [ ] If we do not have php lint in core, should we add it in the composer and made change in the Makefile?

Let me know if my queries make sense?

**Comment by phil-davis** [comment]
This app has a ``stable10`` branch. Probably it needs all sorts of stuff backported from the ``master`` branch. That would include CI script refactorings (Makefile, drone, vendor-bin...)

**Comment by phil-davis** [comment]
PR #89 has backported a current set of CI from configreport ``master`` branch.
@sharidas please rebase this PR and see what happens.

**Comment by phil-davis** [comment]
@sharidas @PVince81 in master the drone matrix had entries for oracle that had been "overwritten" to be acceptance tests. In master, the unit tests were not getting run for oracle.

See PR #90 where I have sorted out the drone matrix. Now that is failing the oracle unit test jobs:
https://drone.owncloud.com/owncloud/configreport/341/24
```
Runtime:       PHP 7.1.23-3+ubuntu16.04.1+deb.sury.org+1
Configuration: /var/www/owncloud/apps/configreport/phpunit.xml
Error:         No code coverage driver is available

..SF                                                                4 / 4 (100%)

Time: 1.02 seconds, Memory: 16.00MB

There was 1 failure:

1) OCA\ConfigReport\Tests\ReportDataCollectorTest::testGetOCTablesArray
Failed asserting that false is true.

/var/www/owncloud/apps/configreport/tests/unit/ReportDataCollectorTest.php:627
```

So I suggest first cherry-pick from PR #90 then add another commit to fix the unit test code in master and make a working PR to master. Then it can be backported into here...

**Comment by sharidas** [comment]
Updated this PR with the changes adopted for unit test `ReportDataCollectorTest.php` from PR https://github.com/owncloud/configreport/pull/91.

**Pull request merged**
