### PR TITLE
Created .travis.yml

### PR DESCRIPTION
**Pull request by Prakharsvnit**

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
the yaml file is invalid - see the log please

````
ERROR: An error occured while trying to parse your .travis.yml file.

Please make sure that the file is valid YAML.

http://lint.travis-ci.org can check your .travis.yml.

The log message was: Build config file had a parse error: could not find expected ':' while scanning a simple key at line 8 column 2.

**Comment by DeepDiver1975** [comment]
getting closed :wink: - please check the logs again - thx

**Comment by Prakharsvnit** [comment]
@DeepDiver1975 the build gives out error "The command "phpunit" exited with 2" .do i need to write 

1.seperate file for phpunit.xml like this one [here](https://github.com/owncloud/oauth2/blob/master/phpunit.xml) and add "script: phpunit --configuration phpunit.xml" in travis.yml or
2.write tests like given [here](https://github.com/owncloud/customgroups/tree/master/tests) and add "script: - cd apps/$APP_NAME/ - make $TEST" in travis.yml file.

How should i go further with this?

**Comment by DeepDiver1975** [comment]
> How should i go further with this?

tests are for sure missing in this repo - they need to be added.
In order to get them properly executed a phpunit.xml is required ....

**Comment by Prakharsvnit** [comment]
@DeepDiver1975 I have started writing tests.link is [here](https://github.com/owncloud/configreport/tree/Prakharsvnit-patch-1-1-1/lib/Tests). Do we need to add [StreamInterface.php](https://github.com/owncloud/updater/blob/master/src/Tests/StreamInterface.php) and [bootstrap.php](https://github.com/owncloud/updater/blob/master/src/Tests/phpunit.xml) like those given in links .

**Comment by PVince81** [comment]
You'll likely need a bootstrap file, yes

**Comment by PVince81** [comment]
incomplete and looks abandoned. Closing

**Pull request closed without merging**
