### PR TITLE
add stats guest_count, renamed count to total_count

### PR DESCRIPTION
**Pull request by JanAckermann**
Show guest count in stats.

Fixes:
- https://github.com/owncloud/enterprise/issues/3467

### CODE REVIEW

**Comment by JanAckermann** [comment]
@phil-davis userTypeHelper available since 10.7 how do we handle this?

**Comment by phil-davis** [comment]
> @phil-davis userTypeHelper available since 10.7 how do we handle this?

@JanAckermann it was only complaining about the var not being declared in the class: https://github.com/owncloud/configreport/pull/146/commits/ae068c1f20e8914fa6c24e04809364c116751c1f

And the acceptance tests against `latest` core should work fine, because the `latest` core release tarball is already 10.7.

I looked at the acceptance tests for 5 seconds - there is only 1 scenario, no interest test cases there! I guess the unit tests cover checking that the output has the expected stuff.

**Comment by JanAckermann** [comment]
Thank you!

**Comment by phil-davis** [comment]
Locally tested with:
```
$ php occ configreport:generate | grep -B 4 -A 8 guest_count
    "stats": {
        "users": {
            "Database": {
                "total_count": 5,
                "guest_count": 0,
                "seen": 5,
                "logged in (30 days)": 1
            }
        },
        "groups": {
            "OC\\Group\\Database": 2
        }
    },
```
There is a `users` section with `total_count` and `guest_count`.

**Review by phil-davis — COMMENTED** [review]
LGTM - @jvillafanez review please.

**Comment by JanAckermann** [comment]
@phil-davis I will bump min version 10.8 since we need a slight change in the core

**Review by jvillafanez — APPROVED** [review]
No workaround for the private class... this will have to do for now.

**Comment by phil-davis** [comment]
Note: https://drone.owncloud.com/owncloud/configreport/1368/4/3

core master needs to say it is at 10.8 - see PR https://github.com/owncloud/core/pull/38745

**Comment by JanAckermann** [comment]
@phil-davis needed to remove latest temporary from drone.star, agree?

**Comment by phil-davis** [comment]
> @phil-davis needed to remove latest temporary from drone.star, agree?

yes - we know that this new configreport code does not work against `latest` = 10.7.0

**Pull request merged**
