### PR TITLE
[stable10] Backport of Include mount information in configreport

### PR DESCRIPTION
**Pull request by sharidas**
Include mount information in the configrepot.

### CODE REVIEW

**Comment by sharidas** [comment]
Original PR : https://github.com/owncloud/configreport/pull/20

**Comment by sharidas** [comment]
Found something wrong here:
https://drone.owncloud.com/owncloud/configreport/388/76 shows a result
```
../../tests/acceptance/run.sh: line 287: /var/www/owncloud/tests/acceptance/../../vendor-bin/behat/vendor/bin/behat: No such file or directory
```

**Comment by sharidas** [comment]
@phil-davis @individual-it I have tried to copy `Makefile` + `behat.yml` + `vendor-bin/behat/composer.json` + `vendor-bin/php_codesniffer/composer.json` as part of  https://github.com/owncloud/configreport/issues/95 in this PR.

**Comment by sharidas** [comment]
@PVince81  in this commit https://github.com/owncloud/configreport/pull/94/commits/7817041661f56ecce94b654c9b11e69d8290870f 
I have copied, files from master branch to stable10 branch to get CI green. @phil-davis @individual-it . Let me know if this change set look ok.

**Comment by sharidas** [comment]
This PR requires a review in commit https://github.com/owncloud/configreport/commit/7817041661f56ecce94b654c9b11e69d8290870f. Let me know if this change looks ok @phil-davis @individual-it @PVince81  

Why this commit requires review:
- CI changes are made for this change set.
   - Tried to copy the changes from master branch to the stable10.

**Comment by phil-davis** [comment]
@sharidas I cherry-picked the CI-related commits to PR #97 and merged that. Somehow I have to remember which apps have to have `stable10` backports.

I have rebased this PR. The CI-related commit disappeared, so you did have the correct code edits!

If CI is green here then it is good to merge.

**Pull request merged**
